/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.formula.api;

import org.junit.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class AppTest {

	@Test 
	public void testAppHasAGreeting() {
		App classUnderTest = new App();
	}
}
